/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export interface Alert {
  id: string;
  name: string;
  price: number;
  symbol: string;
}
