/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export type PostAlertBody = {
  /** Name of the alert */
  name: string;
  /** Price to buy in USD */
  price: number;
  /** Symbol of the coin */
  symbol: string;
};
