/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthLogin200 = {
  /** Id of the user */
  _id: string;
  /** Date of creation */
  createdAt: string;
  /** Email of the user */
  email: string;
  /** Name of the user */
  name: string;
};
