/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * crypto alert
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

export const postAuthRegisterBodyPasswordMin = 6;


export const postAuthRegisterBody = zod.object({
  "name": zod.string(),
  "email": zod.string().email(),
  "password": zod.string().min(postAuthRegisterBodyPasswordMin)
})

export const postAuthRegisterResponse = zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string().email(),
  "createdAt": zod.string()
})

export const postAuthLoginBodyPasswordMin = 6;


export const postAuthLoginBody = zod.object({
  "email": zod.string().email(),
  "password": zod.string().min(postAuthLoginBodyPasswordMin)
})

export const postAuthLoginResponse = zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string().email(),
  "createdAt": zod.string()
})

export const postAuthLogoutResponse = zod.object({
  "message": zod.string()
})

export const postAlertBody = zod.object({
  "name": zod.string(),
  "price": zod.number(),
  "symbol": zod.string()
})

export const postAlertResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "price": zod.number(),
  "symbol": zod.string()
})

export const getAlertIdParams = zod.object({
  "id": zod.string()
})

export const getAlertIdResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "price": zod.number(),
  "symbol": zod.string()
})

export const getCryptoSymbolParams = zod.object({
  "symbol": zod.string()
})

export const getCryptoSymbolResponse = zod.object({
  "symbol": zod.string(),
  "price": zod.string(),
  "date": zod.string()
})

export const getUserMeResponse = zod.object({
  "_id": zod.string(),
  "name": zod.string(),
  "email": zod.string().email(),
  "createdAt": zod.string()
})

