/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Template
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthLoginBody = {
  /** Email of the user */
  email: string;
  /**
   * Password of the user
   * @minLength 6
   */
  password: string;
};
